#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TouchWalkthrough.Resource", IsApplication=true)]

namespace TouchWalkthrough
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int filter_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int filter_button_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int filter_button_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_launcher = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int karte = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int plus_button_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int plus_button_pressed = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int Button_filter = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Button_plus = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int buttonInteraktion = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int demoImageView = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int filterLayout = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int plus_filter_buttons_Layout = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout_filter_geoeffnet = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layout_filter_plus = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int layout_karte = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int gestures = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int activity_custom_gesture_recognizer = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int activity_gesture_recognizer = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int activity_touch_sample = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
