#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TouchWalkthrough.Resource", IsApplication=true)]

namespace TouchWalkthrough
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int planets_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_left_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_right_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int filter_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int history_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_hap1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_hap2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_hap3 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int karte = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Karte_Gebaeude = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Karte_Z_EG = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int logo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int plus_button = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int RelativeLayoutMap = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int ViewIsOnlyForAlphaValueBackground = 2131165197;
			
			// aapt resource value: 0x7f070016
			public const int ViewIsOnlyForAlphaValueBackground2 = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int editText1 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int editText2 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int editText3 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int editText4 = 2131165212;
			
			// aapt resource value: 0x7f070015
			public const int frameLayoutFilter = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int gestureRecognizerView1 = 2131165207;
			
			// aapt resource value: 0x7f070007
			public const int historyList = 2131165191;
			
			// aapt resource value: 0x7f070010
			public const int imageButton1 = 2131165200;
			
			// aapt resource value: 0x7f070006
			public const int imageButton122 = 2131165190;
			
			// aapt resource value: 0x7f07000f
			public const int imageButton2 = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int imageButton3 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int imageButton4 = 2131165203;
			
			// aapt resource value: 0x7f070011
			public const int imageButton5 = 2131165201;
			
			// aapt resource value: 0x7f07000b
			public const int imageButton6 = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int imageButton97 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int imageButton98 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int imageButton99 = 2131165188;
			
			// aapt resource value: 0x7f07001d
			public const int imageView1 = 2131165213;
			
			// aapt resource value: 0x7f07000a
			public const int imageViewKarte = 2131165194;
			
			// aapt resource value: 0x7f070018
			public const int layoutPlus_Menue = 2131165208;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout = 2131165192;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayout1 = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int linearLayoutFilter = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int linearLayoutHistory = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int relativeLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070014
			public const int relativeLayoutFilter = 2131165204;
			
			// aapt resource value: 0x7f07000c
			public const int relativeLayout_navbar = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Filter_Menue = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int History = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainTestGestureRecognizer = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Plus_Menue = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int gestures = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int activity_custom_gesture_recognizer = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int activity_gesture_recognizer = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int activity_touch_sample = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int planet_prompt = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
