#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TouchWalkthrough.Resource", IsApplication=true)]

namespace TouchWalkthrough
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_left_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_right_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int aufmap_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int beispielbild = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dropart1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int filter_button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int haken = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int history_button = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_hap1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_hap1_off = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_hap2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_hap2_off = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_hap3 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_hap3_off = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int karte_z_eg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int kreuz = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int logo = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int navbar_background = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int plus_button = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int switch1 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int switch2 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int wann_icon = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060042
			public const int DateAndTime = 2131099714;
			
			// aapt resource value: 0x7f06002a
			public const int Heading = 2131099690;
			
			// aapt resource value: 0x7f060003
			public const int Image = 2131099651;
			
			// aapt resource value: 0x7f06002f
			public const int ImageViewKarte = 2131099695;
			
			// aapt resource value: 0x7f06003e
			public const int LinearFileFotoPick = 2131099710;
			
			// aapt resource value: 0x7f060055
			public const int LinearFileFotoPick2 = 2131099733;
			
			// aapt resource value: 0x7f06002b
			public const int List = 2131099691;
			
			// aapt resource value: 0x7f06003c
			public const int RelLayoutdropplazieren = 2131099708;
			
			// aapt resource value: 0x7f06002d
			public const int RelativeLayoutMap = 2131099693;
			
			// aapt resource value: 0x7f060000
			public const int Text = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Text1 = 2131099649;
			
			// aapt resource value: 0x7f06003b
			public const int Text12 = 2131099707;
			
			// aapt resource value: 0x7f060002
			public const int Text2 = 2131099650;
			
			// aapt resource value: 0x7f06003f
			public const int Text3 = 2131099711;
			
			// aapt resource value: 0x7f060048
			public const int Text46 = 2131099720;
			
			// aapt resource value: 0x7f060039
			public const int ViewIsOnlyForAlphaValueBackground2 = 2131099705;
			
			// aapt resource value: 0x7f060022
			public const int button1 = 2131099682;
			
			// aapt resource value: 0x7f06000b
			public const int button2 = 2131099659;
			
			// aapt resource value: 0x7f060040
			public const int button3 = 2131099712;
			
			// aapt resource value: 0x7f06004f
			public const int datePicker1 = 2131099727;
			
			// aapt resource value: 0x7f060052
			public const int datePicker2 = 2131099730;
			
			// aapt resource value: 0x7f060038
			public const int frameLayoutFilter = 2131099704;
			
			// aapt resource value: 0x7f060047
			public const int ganztaegig = 2131099719;
			
			// aapt resource value: 0x7f06003a
			public const int gestureRecognizerView1 = 2131099706;
			
			// aapt resource value: 0x7f060029
			public const int historyList = 2131099689;
			
			// aapt resource value: 0x7f060033
			public const int imageButton1 = 2131099699;
			
			// aapt resource value: 0x7f060028
			public const int imageButton122 = 2131099688;
			
			// aapt resource value: 0x7f060032
			public const int imageButton2 = 2131099698;
			
			// aapt resource value: 0x7f060035
			public const int imageButton3 = 2131099701;
			
			// aapt resource value: 0x7f060043
			public const int imageButton33 = 2131099715;
			
			// aapt resource value: 0x7f060014
			public const int imageButton367 = 2131099668;
			
			// aapt resource value: 0x7f060036
			public const int imageButton4 = 2131099702;
			
			// aapt resource value: 0x7f060045
			public const int imageButton44 = 2131099717;
			
			// aapt resource value: 0x7f060015
			public const int imageButton467 = 2131099669;
			
			// aapt resource value: 0x7f060034
			public const int imageButton5 = 2131099700;
			
			// aapt resource value: 0x7f060044
			public const int imageButton55 = 2131099716;
			
			// aapt resource value: 0x7f060013
			public const int imageButton567 = 2131099667;
			
			// aapt resource value: 0x7f060006
			public const int imageButton568 = 2131099654;
			
			// aapt resource value: 0x7f06001b
			public const int imageButton569 = 2131099675;
			
			// aapt resource value: 0x7f060017
			public const int imageButton5694 = 2131099671;
			
			// aapt resource value: 0x7f06000e
			public const int imageButton5695 = 2131099662;
			
			// aapt resource value: 0x7f06001e
			public const int imageButton5696 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int imageButton5697 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int imageButton5698 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int imageButton5699 = 2131099681;
			
			// aapt resource value: 0x7f060046
			public const int imageButton572 = 2131099718;
			
			// aapt resource value: 0x7f06002e
			public const int imageButton6 = 2131099694;
			
			// aapt resource value: 0x7f060024
			public const int imageButton97 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int imageButton98 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int imageButton99 = 2131099686;
			
			// aapt resource value: 0x7f060007
			public const int imageView1 = 2131099655;
			
			// aapt resource value: 0x7f06001d
			public const int imageView2 = 2131099677;
			
			// aapt resource value: 0x7f060004
			public const int lRelLayout23 = 2131099652;
			
			// aapt resource value: 0x7f06002c
			public const int linearLayout = 2131099692;
			
			// aapt resource value: 0x7f060031
			public const int linearLayout1 = 2131099697;
			
			// aapt resource value: 0x7f060012
			public const int linearLayout11 = 2131099666;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout12 = 2131099656;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayout13 = 2131099674;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout133 = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout134 = 2131099660;
			
			// aapt resource value: 0x7f060016
			public const int linearLayout135 = 2131099670;
			
			// aapt resource value: 0x7f06004d
			public const int linearLayout14 = 2131099725;
			
			// aapt resource value: 0x7f060053
			public const int linearLayout143 = 2131099731;
			
			// aapt resource value: 0x7f06004c
			public const int linearLayout15 = 2131099724;
			
			// aapt resource value: 0x7f060023
			public const int linearLayoutFilter = 2131099683;
			
			// aapt resource value: 0x7f060027
			public const int linearLayoutHistory = 2131099687;
			
			// aapt resource value: 0x7f060041
			public const int relLayout2 = 2131099713;
			
			// aapt resource value: 0x7f06001c
			public const int relativeLayout1 = 2131099676;
			
			// aapt resource value: 0x7f060037
			public const int relativeLayoutFilter = 2131099703;
			
			// aapt resource value: 0x7f060005
			public const int relativeLayoutTop = 2131099653;
			
			// aapt resource value: 0x7f060030
			public const int relativeLayout_navbar = 2131099696;
			
			// aapt resource value: 0x7f060011
			public const int relativeLayout_navbar2 = 2131099665;
			
			// aapt resource value: 0x7f060049
			public const int schiebtSwitchRechts = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int switch_button = 2131099722;
			
			// aapt resource value: 0x7f060010
			public const int textView1 = 2131099664;
			
			// aapt resource value: 0x7f060009
			public const int textView22 = 2131099657;
			
			// aapt resource value: 0x7f060018
			public const int textView23 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int textView24 = 2131099673;
			
			// aapt resource value: 0x7f06000f
			public const int textView25 = 2131099663;
			
			// aapt resource value: 0x7f060051
			public const int textView29 = 2131099729;
			
			// aapt resource value: 0x7f06000a
			public const int textView3 = 2131099658;
			
			// aapt resource value: 0x7f060054
			public const int textView33 = 2131099732;
			
			// aapt resource value: 0x7f06004b
			public const int textView34 = 2131099723;
			
			// aapt resource value: 0x7f06003d
			public const int textView35 = 2131099709;
			
			// aapt resource value: 0x7f060050
			public const int textView36 = 2131099728;
			
			// aapt resource value: 0x7f06004e
			public const int textView39 = 2131099726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DropDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Filter_Menue = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int History = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HomeScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainTestGestureRecognizer = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Plus_Menue = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int gestures = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int activity_custom_gesture_recognizer = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int activity_gesture_recognizer = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int activity_touch_sample = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
